# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1023, 505)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 4, 1017, 467))
        self.widget.setObjectName("widget")
        self.main_layout = QtWidgets.QVBoxLayout(self.widget)
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.output_layot = QtWidgets.QVBoxLayout()
        self.output_layot.setObjectName("output_layot")
        self.top_outpyt_layout = QtWidgets.QHBoxLayout()
        self.top_outpyt_layout.setObjectName("top_outpyt_layout")
        self.input_line = QtWidgets.QLineEdit(self.widget)
        self.input_line.setObjectName("input_line")
        self.top_outpyt_layout.addWidget(self.input_line)
        self.end_box = QtWidgets.QComboBox(self.widget)
        self.end_box.setObjectName("end_box")
        self.end_box.addItem("")
        self.end_box.addItem("")
        self.end_box.addItem("")
        self.end_box.addItem("")
        self.top_outpyt_layout.addWidget(self.end_box)
        self.send_btn = QtWidgets.QPushButton(self.widget)
        self.send_btn.setObjectName("send_btn")
        self.top_outpyt_layout.addWidget(self.send_btn)
        self.output_layot.addLayout(self.top_outpyt_layout)
        self.out_view = QtWidgets.QColumnView(self.widget)
        self.out_view.setFrameShadow(QtWidgets.QFrame.Plain)
        self.out_view.setLineWidth(1)
        self.out_view.setTextElideMode(QtCore.Qt.ElideNone)
        self.out_view.setObjectName("out_view")
        self.output_layot.addWidget(self.out_view)
        self.bottom_output_layout = QtWidgets.QHBoxLayout()
        self.bottom_output_layout.setObjectName("bottom_output_layout")
        self.time_chk = QtWidgets.QCheckBox(self.widget)
        self.time_chk.setObjectName("time_chk")
        self.bottom_output_layout.addWidget(self.time_chk)
        self.scroll_chk = QtWidgets.QCheckBox(self.widget)
        self.scroll_chk.setObjectName("scroll_chk")
        self.bottom_output_layout.addWidget(self.scroll_chk)
        spacerItem = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_output_layout.addItem(spacerItem)
        self.clear_btn = QtWidgets.QPushButton(self.widget)
        self.clear_btn.setObjectName("clear_btn")
        self.bottom_output_layout.addWidget(self.clear_btn)
        self.output_layot.addLayout(self.bottom_output_layout)
        self.main_layout.addLayout(self.output_layot)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setLineWidth(10)
        self.line.setMidLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_layout.addWidget(self.line)
        self.pref_layout = QtWidgets.QVBoxLayout()
        self.pref_layout.setObjectName("pref_layout")
        self.port_pref_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.port_pref_label.setFont(font)
        self.port_pref_label.setAlignment(QtCore.Qt.AlignCenter)
        self.port_pref_label.setObjectName("port_pref_label")
        self.pref_layout.addWidget(self.port_pref_label)
        self.port_layout = QtWidgets.QHBoxLayout()
        self.port_layout.setObjectName("port_layout")
        self.port_switch_label = QtWidgets.QLabel(self.widget)
        self.port_switch_label.setObjectName("port_switch_label")
        self.port_layout.addWidget(self.port_switch_label)
        self.port_box = QtWidgets.QComboBox(self.widget)
        self.port_box.setObjectName("port_box")
        self.port_layout.addWidget(self.port_box)
        self.input_sep_label = QtWidgets.QLabel(self.widget)
        self.input_sep_label.setObjectName("input_sep_label")
        self.port_layout.addWidget(self.input_sep_label)
        self.input_sep_box = QtWidgets.QComboBox(self.widget)
        self.input_sep_box.setEditable(True)
        self.input_sep_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.input_sep_box.setIconSize(QtCore.QSize(16, 16))
        self.input_sep_box.setObjectName("input_sep_box")
        self.input_sep_box.addItem("")
        self.input_sep_box.addItem("")
        self.input_sep_box.addItem("")
        self.port_layout.addWidget(self.input_sep_box)
        self.baudreate_label = QtWidgets.QLabel(self.widget)
        self.baudreate_label.setObjectName("baudreate_label")
        self.port_layout.addWidget(self.baudreate_label)
        self.baudrate_box = QtWidgets.QComboBox(self.widget)
        self.baudrate_box.setEditable(False)
        self.baudrate_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.baudrate_box.setObjectName("baudrate_box")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.port_layout.addWidget(self.baudrate_box)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.port_layout.addItem(spacerItem1)
        self.connect_btn = QtWidgets.QPushButton(self.widget)
        self.connect_btn.setObjectName("connect_btn")
        self.port_layout.addWidget(self.connect_btn)
        self.pref_layout.addLayout(self.port_layout)
        self.main_layout.addLayout(self.pref_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionexport_as = QtWidgets.QAction(MainWindow)
        self.actionexport_as.setObjectName("actionexport_as")

        self.retranslateUi(MainWindow)
        self.baudrate_box.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Монитор последовательного порта"))
        self.end_box.setItemText(0, _translate("MainWindow", "-"))
        self.end_box.setItemText(1, _translate("MainWindow", "\\n\\r"))
        self.end_box.setItemText(2, _translate("MainWindow", "\\n"))
        self.end_box.setItemText(3, _translate("MainWindow", "\\r"))
        self.send_btn.setText(_translate("MainWindow", "Отправить"))
        self.time_chk.setText(_translate("MainWindow", "Автопрокрутка"))
        self.scroll_chk.setText(_translate("MainWindow", "Добавлять отметки времени"))
        self.clear_btn.setText(_translate("MainWindow", "Очистить"))
        self.port_pref_label.setText(_translate("MainWindow", "Настройки подключения"))
        self.port_switch_label.setText(_translate("MainWindow", "Порт"))
        self.input_sep_label.setText(_translate("MainWindow", "Разделитель"))
        self.input_sep_box.setItemText(0, _translate("MainWindow", ";"))
        self.input_sep_box.setItemText(1, _translate("MainWindow", ","))
        self.input_sep_box.setItemText(2, _translate("MainWindow", "\\t"))
        self.baudreate_label.setText(_translate("MainWindow", "Скорость соединения"))
        self.baudrate_box.setItemText(0, _translate("MainWindow", "300 бод"))
        self.baudrate_box.setItemText(1, _translate("MainWindow", "1200 бод"))
        self.baudrate_box.setItemText(2, _translate("MainWindow", "2400 бод"))
        self.baudrate_box.setItemText(3, _translate("MainWindow", "4800 бод"))
        self.baudrate_box.setItemText(4, _translate("MainWindow", "9600 бод"))
        self.baudrate_box.setItemText(5, _translate("MainWindow", "19200 бод"))
        self.baudrate_box.setItemText(6, _translate("MainWindow", "38400 бод"))
        self.baudrate_box.setItemText(7, _translate("MainWindow", "57600 бод"))
        self.baudrate_box.setItemText(8, _translate("MainWindow", "74880 бод"))
        self.baudrate_box.setItemText(9, _translate("MainWindow", "115200 бод"))
        self.baudrate_box.setItemText(10, _translate("MainWindow", "230400 бод"))
        self.baudrate_box.setItemText(11, _translate("MainWindow", "250000 бод"))
        self.baudrate_box.setItemText(12, _translate("MainWindow", "500000 бод"))
        self.baudrate_box.setItemText(13, _translate("MainWindow", "1000000 бод"))
        self.baudrate_box.setItemText(14, _translate("MainWindow", "2000000 бод"))
        self.connect_btn.setText(_translate("MainWindow", "Подключиться"))
        self.actionexport_as.setText(_translate("MainWindow", "export as..."))
