# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(928, 490)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setObjectName("tab_widget")
        self.io_tab = QtWidgets.QWidget()
        self.io_tab.setObjectName("io_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.io_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.output_layot = QtWidgets.QVBoxLayout()
        self.output_layot.setObjectName("output_layot")
        self.top_outpyt_layout = QtWidgets.QHBoxLayout()
        self.top_outpyt_layout.setObjectName("top_outpyt_layout")
        self.input_line = QtWidgets.QLineEdit(self.io_tab)
        self.input_line.setObjectName("input_line")
        self.top_outpyt_layout.addWidget(self.input_line)
        self.end_box = QtWidgets.QComboBox(self.io_tab)
        self.end_box.setObjectName("end_box")
        self.end_box.addItem("")
        self.end_box.setItemText(0, "")
        self.end_box.addItem("")
        self.end_box.addItem("")
        self.end_box.addItem("")
        self.top_outpyt_layout.addWidget(self.end_box)
        self.send_btn = QtWidgets.QPushButton(self.io_tab)
        self.send_btn.setEnabled(False)
        self.send_btn.setCheckable(False)
        self.send_btn.setDefault(True)
        self.send_btn.setObjectName("send_btn")
        self.top_outpyt_layout.addWidget(self.send_btn)
        self.output_layot.addLayout(self.top_outpyt_layout)
        self.out_field = QtWidgets.QTableView(self.io_tab)
        self.out_field.setObjectName("out_field")
        self.output_layot.addWidget(self.out_field)
        self.bottom_output_layout = QtWidgets.QHBoxLayout()
        self.bottom_output_layout.setObjectName("bottom_output_layout")
        self.scroll_chk = QtWidgets.QCheckBox(self.io_tab)
        self.scroll_chk.setChecked(True)
        self.scroll_chk.setObjectName("scroll_chk")
        self.bottom_output_layout.addWidget(self.scroll_chk)
        self.time_chk = QtWidgets.QCheckBox(self.io_tab)
        self.time_chk.setObjectName("time_chk")
        self.bottom_output_layout.addWidget(self.time_chk)
        spacerItem = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_output_layout.addItem(spacerItem)
        self.clear_btn = QtWidgets.QPushButton(self.io_tab)
        self.clear_btn.setObjectName("clear_btn")
        self.bottom_output_layout.addWidget(self.clear_btn)
        self.output_layot.addLayout(self.bottom_output_layout)
        self.verticalLayout.addLayout(self.output_layot)
        self.pref_layout = QtWidgets.QVBoxLayout()
        self.pref_layout.setObjectName("pref_layout")
        self.port_pref_label = QtWidgets.QLabel(self.io_tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.port_pref_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(False)
        self.port_pref_label.setFont(font)
        self.port_pref_label.setAutoFillBackground(True)
        self.port_pref_label.setFrameShape(QtWidgets.QFrame.Box)
        self.port_pref_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.port_pref_label.setLineWidth(0)
        self.port_pref_label.setMidLineWidth(1)
        self.port_pref_label.setAlignment(QtCore.Qt.AlignCenter)
        self.port_pref_label.setObjectName("port_pref_label")
        self.pref_layout.addWidget(self.port_pref_label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.port_switch_label = QtWidgets.QLabel(self.io_tab)
        self.port_switch_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.port_switch_label.setObjectName("port_switch_label")
        self.gridLayout.addWidget(self.port_switch_label, 0, 0, 1, 1)
        self.refresh_btn = QtWidgets.QPushButton(self.io_tab)
        self.refresh_btn.setObjectName("refresh_btn")
        self.gridLayout.addWidget(self.refresh_btn, 0, 2, 1, 1)
        self.baudrate_box = QtWidgets.QComboBox(self.io_tab)
        self.baudrate_box.setEditable(False)
        self.baudrate_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.baudrate_box.setObjectName("baudrate_box")
        self.gridLayout.addWidget(self.baudrate_box, 1, 1, 1, 1)
        self.connect_btn = QtWidgets.QPushButton(self.io_tab)
        self.connect_btn.setCheckable(False)
        self.connect_btn.setObjectName("connect_btn")
        self.gridLayout.addWidget(self.connect_btn, 0, 7, 1, 1)
        self.port_box = QtWidgets.QComboBox(self.io_tab)
        self.port_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.port_box.setObjectName("port_box")
        self.gridLayout.addWidget(self.port_box, 0, 1, 1, 1)
        self.input_delim_label = QtWidgets.QLabel(self.io_tab)
        self.input_delim_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_delim_label.setObjectName("input_delim_label")
        self.gridLayout.addWidget(self.input_delim_label, 0, 3, 1, 1)
        self.input_delim_box = QtWidgets.QComboBox(self.io_tab)
        self.input_delim_box.setEditable(False)
        self.input_delim_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.input_delim_box.setIconSize(QtCore.QSize(16, 16))
        self.input_delim_box.setObjectName("input_delim_box")
        self.input_delim_box.addItem("")
        self.input_delim_box.addItem("")
        self.input_delim_box.addItem("")
        self.gridLayout.addWidget(self.input_delim_box, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 2)
        self.baudreate_label = QtWidgets.QLabel(self.io_tab)
        self.baudreate_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.baudreate_label.setObjectName("baudreate_label")
        self.gridLayout.addWidget(self.baudreate_label, 1, 0, 1, 1)
        self.pref_layout.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.pref_layout)
        self.tab_widget.addTab(self.io_tab, "")
        self.export_tab = QtWidgets.QWidget()
        self.export_tab.setObjectName("export_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.export_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.export_tab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.dsv_layout = QtWidgets.QGridLayout()
        self.dsv_layout.setObjectName("dsv_layout")
        self.dsv_delim_label = QtWidgets.QLabel(self.export_tab)
        self.dsv_delim_label.setObjectName("dsv_delim_label")
        self.dsv_layout.addWidget(self.dsv_delim_label, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dsv_layout.addItem(spacerItem2, 0, 4, 1, 1)
        self.dsv_quote_box = QtWidgets.QComboBox(self.export_tab)
        self.dsv_quote_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.dsv_quote_box.setObjectName("dsv_quote_box")
        self.dsv_quote_box.addItem("")
        self.dsv_quote_box.addItem("")
        self.dsv_layout.addWidget(self.dsv_quote_box, 0, 3, 1, 1)
        self.dsv_delim_box = QtWidgets.QComboBox(self.export_tab)
        self.dsv_delim_box.setObjectName("dsv_delim_box")
        self.dsv_delim_box.addItem("")
        self.dsv_delim_box.addItem("")
        self.dsv_delim_box.addItem("")
        self.dsv_delim_box.addItem("")
        self.dsv_layout.addWidget(self.dsv_delim_box, 0, 1, 1, 1)
        self.dsv_export_btn = QtWidgets.QPushButton(self.export_tab)
        self.dsv_export_btn.setObjectName("dsv_export_btn")
        self.dsv_layout.addWidget(self.dsv_export_btn, 0, 5, 1, 1)
        self.dsv_quote_label = QtWidgets.QLabel(self.export_tab)
        self.dsv_quote_label.setObjectName("dsv_quote_label")
        self.dsv_layout.addWidget(self.dsv_quote_label, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.dsv_layout)
        self.label = QtWidgets.QLabel(self.export_tab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.sql_layout = QtWidgets.QGridLayout()
        self.sql_layout.setObjectName("sql_layout")
        self.sql_new_table_btn = QtWidgets.QPushButton(self.export_tab)
        self.sql_new_table_btn.setEnabled(False)
        self.sql_new_table_btn.setObjectName("sql_new_table_btn")
        self.sql_layout.addWidget(self.sql_new_table_btn, 1, 1, 1, 1)
        self.sql_connect_btn = QtWidgets.QPushButton(self.export_tab)
        self.sql_connect_btn.setObjectName("sql_connect_btn")
        self.sql_layout.addWidget(self.sql_connect_btn, 0, 0, 1, 1)
        self.sql_table_box = QtWidgets.QComboBox(self.export_tab)
        self.sql_table_box.setEnabled(False)
        self.sql_table_box.setObjectName("sql_table_box")
        self.sql_layout.addWidget(self.sql_table_box, 0, 1, 1, 1)
        self.sql_add_btn = QtWidgets.QPushButton(self.export_tab)
        self.sql_add_btn.setEnabled(False)
        self.sql_add_btn.setObjectName("sql_add_btn")
        self.sql_layout.addWidget(self.sql_add_btn, 0, 2, 1, 1)
        self.sql_overwrite_btn = QtWidgets.QPushButton(self.export_tab)
        self.sql_overwrite_btn.setEnabled(False)
        self.sql_overwrite_btn.setObjectName("sql_overwrite_btn")
        self.sql_layout.addWidget(self.sql_overwrite_btn, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.sql_layout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.tab_widget.addTab(self.export_tab, "")
        self.verticalLayout_4.addWidget(self.tab_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        self.end_box.setCurrentIndex(1)
        self.baudrate_box.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Монитор последовательного порта"))
        self.end_box.setItemText(1, _translate("MainWindow", "\\n\\r"))
        self.end_box.setItemText(2, _translate("MainWindow", "\\n"))
        self.end_box.setItemText(3, _translate("MainWindow", "\\r"))
        self.send_btn.setText(_translate("MainWindow", "Отправить"))
        self.scroll_chk.setText(_translate("MainWindow", "Автопрокрутка"))
        self.time_chk.setText(_translate("MainWindow", "Добавлять отметки времени"))
        self.clear_btn.setText(_translate("MainWindow", "Очистить"))
        self.port_pref_label.setText(_translate("MainWindow", "Настройки подключения"))
        self.port_switch_label.setText(_translate("MainWindow", "Порт"))
        self.refresh_btn.setText(_translate("MainWindow", "Обновить"))
        self.connect_btn.setText(_translate("MainWindow", "Подключиться"))
        self.input_delim_label.setText(_translate("MainWindow", "Разделитель"))
        self.input_delim_box.setItemText(0, _translate("MainWindow", ";"))
        self.input_delim_box.setItemText(1, _translate("MainWindow", ","))
        self.input_delim_box.setItemText(2, _translate("MainWindow", "\\t"))
        self.baudreate_label.setText(_translate("MainWindow", "Скорость"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.io_tab), _translate("MainWindow", "Соединение"))
        self.label_2.setText(_translate("MainWindow", "DSV"))
        self.dsv_delim_label.setText(_translate("MainWindow", "Разделитель"))
        self.dsv_quote_box.setItemText(0, _translate("MainWindow", "\""))
        self.dsv_quote_box.setItemText(1, _translate("MainWindow", "\'"))
        self.dsv_delim_box.setItemText(0, _translate("MainWindow", ","))
        self.dsv_delim_box.setItemText(1, _translate("MainWindow", "\\t"))
        self.dsv_delim_box.setItemText(2, _translate("MainWindow", ";"))
        self.dsv_delim_box.setItemText(3, _translate("MainWindow", ":"))
        self.dsv_export_btn.setText(_translate("MainWindow", "Экспорт..."))
        self.dsv_quote_label.setText(_translate("MainWindow", "Quotechar"))
        self.label.setText(_translate("MainWindow", "SQL database"))
        self.sql_new_table_btn.setText(_translate("MainWindow", "Новая таблица..."))
        self.sql_connect_btn.setText(_translate("MainWindow", "Подключить базу данных..."))
        self.sql_add_btn.setText(_translate("MainWindow", "Добавить в конец"))
        self.sql_overwrite_btn.setText(_translate("MainWindow", "Перезаписать"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.export_tab), _translate("MainWindow", "Экспорт"))
