# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(983, 510)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setObjectName("tab_widget")
        self.io_tab = QtWidgets.QWidget()
        self.io_tab.setObjectName("io_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.io_tab)
        self.verticalLayout.setContentsMargins(10, 6, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.output_layot = QtWidgets.QVBoxLayout()
        self.output_layot.setObjectName("output_layot")
        self.top_outpyt_layout = QtWidgets.QHBoxLayout()
        self.top_outpyt_layout.setObjectName("top_outpyt_layout")
        self.input_line = QtWidgets.QLineEdit(self.io_tab)
        self.input_line.setObjectName("input_line")
        self.top_outpyt_layout.addWidget(self.input_line)
        self.end_box = QtWidgets.QComboBox(self.io_tab)
        self.end_box.setObjectName("end_box")
        self.end_box.addItem("")
        self.end_box.setItemText(0, "")
        self.end_box.addItem("")
        self.end_box.addItem("")
        self.end_box.addItem("")
        self.top_outpyt_layout.addWidget(self.end_box)
        self.send_btn = QtWidgets.QPushButton(self.io_tab)
        self.send_btn.setEnabled(False)
        self.send_btn.setCheckable(False)
        self.send_btn.setDefault(True)
        self.send_btn.setObjectName("send_btn")
        self.top_outpyt_layout.addWidget(self.send_btn)
        self.output_layot.addLayout(self.top_outpyt_layout)
        self.column_view = QtWidgets.QColumnView(self.io_tab)
        self.column_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.column_view.setProperty("showDropIndicator", True)
        self.column_view.setObjectName("column_view")
        self.output_layot.addWidget(self.column_view)
        self.bottom_output_layout = QtWidgets.QHBoxLayout()
        self.bottom_output_layout.setObjectName("bottom_output_layout")
        self.time_chk = QtWidgets.QCheckBox(self.io_tab)
        self.time_chk.setChecked(True)
        self.time_chk.setObjectName("time_chk")
        self.bottom_output_layout.addWidget(self.time_chk)
        self.scroll_chk = QtWidgets.QCheckBox(self.io_tab)
        self.scroll_chk.setObjectName("scroll_chk")
        self.bottom_output_layout.addWidget(self.scroll_chk)
        spacerItem = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_output_layout.addItem(spacerItem)
        self.clear_btn = QtWidgets.QPushButton(self.io_tab)
        self.clear_btn.setObjectName("clear_btn")
        self.bottom_output_layout.addWidget(self.clear_btn)
        self.output_layot.addLayout(self.bottom_output_layout)
        self.verticalLayout.addLayout(self.output_layot)
        self.pref_layout = QtWidgets.QVBoxLayout()
        self.pref_layout.setObjectName("pref_layout")
        self.port_pref_label = QtWidgets.QLabel(self.io_tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.port_pref_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(False)
        self.port_pref_label.setFont(font)
        self.port_pref_label.setAutoFillBackground(True)
        self.port_pref_label.setFrameShape(QtWidgets.QFrame.Box)
        self.port_pref_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.port_pref_label.setLineWidth(0)
        self.port_pref_label.setMidLineWidth(1)
        self.port_pref_label.setAlignment(QtCore.Qt.AlignCenter)
        self.port_pref_label.setObjectName("port_pref_label")
        self.pref_layout.addWidget(self.port_pref_label)
        self.port_layout = QtWidgets.QHBoxLayout()
        self.port_layout.setObjectName("port_layout")
        self.port_switch_label = QtWidgets.QLabel(self.io_tab)
        self.port_switch_label.setObjectName("port_switch_label")
        self.port_layout.addWidget(self.port_switch_label)
        self.port_box = QtWidgets.QComboBox(self.io_tab)
        self.port_box.setObjectName("port_box")
        self.port_layout.addWidget(self.port_box)
        self.input_delim_label = QtWidgets.QLabel(self.io_tab)
        self.input_delim_label.setObjectName("input_delim_label")
        self.port_layout.addWidget(self.input_delim_label)
        self.input_delim_box = QtWidgets.QComboBox(self.io_tab)
        self.input_delim_box.setEditable(True)
        self.input_delim_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.input_delim_box.setIconSize(QtCore.QSize(16, 16))
        self.input_delim_box.setObjectName("input_delim_box")
        self.input_delim_box.addItem("")
        self.input_delim_box.addItem("")
        self.input_delim_box.addItem("")
        self.port_layout.addWidget(self.input_delim_box)
        self.baudreate_label = QtWidgets.QLabel(self.io_tab)
        self.baudreate_label.setObjectName("baudreate_label")
        self.port_layout.addWidget(self.baudreate_label)
        self.baudrate_box = QtWidgets.QComboBox(self.io_tab)
        self.baudrate_box.setEditable(False)
        self.baudrate_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.baudrate_box.setObjectName("baudrate_box")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.port_layout.addWidget(self.baudrate_box)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.port_layout.addItem(spacerItem1)
        self.connect_btn = QtWidgets.QPushButton(self.io_tab)
        self.connect_btn.setCheckable(True)
        self.connect_btn.setObjectName("connect_btn")
        self.port_layout.addWidget(self.connect_btn)
        self.pref_layout.addLayout(self.port_layout)
        self.verticalLayout.addLayout(self.pref_layout)
        self.tab_widget.addTab(self.io_tab, "")
        self.export_tab = QtWidgets.QWidget()
        self.export_tab.setObjectName("export_tab")
        self.tab_widget.addTab(self.export_tab, "")
        self.verticalLayout_2.addWidget(self.tab_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionexport_as = QtWidgets.QAction(MainWindow)
        self.actionexport_as.setObjectName("actionexport_as")

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        self.end_box.setCurrentIndex(1)
        self.baudrate_box.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Монитор последовательного порта"))
        self.end_box.setItemText(1, _translate("MainWindow", "\\n\\r"))
        self.end_box.setItemText(2, _translate("MainWindow", "\\n"))
        self.end_box.setItemText(3, _translate("MainWindow", "\\r"))
        self.send_btn.setText(_translate("MainWindow", "Отправить"))
        self.time_chk.setText(_translate("MainWindow", "Автопрокрутка"))
        self.scroll_chk.setText(_translate("MainWindow", "Добавлять отметки времени"))
        self.clear_btn.setText(_translate("MainWindow", "Очистить"))
        self.port_pref_label.setText(_translate("MainWindow", "Настройки подключения"))
        self.port_switch_label.setText(_translate("MainWindow", "Порт"))
        self.input_delim_label.setText(_translate("MainWindow", "Разделитель"))
        self.input_delim_box.setItemText(0, _translate("MainWindow", ";"))
        self.input_delim_box.setItemText(1, _translate("MainWindow", ","))
        self.input_delim_box.setItemText(2, _translate("MainWindow", "\\t"))
        self.baudreate_label.setText(_translate("MainWindow", "Скорость соединения"))
        self.baudrate_box.setItemText(0, _translate("MainWindow", "300 бод"))
        self.baudrate_box.setItemText(1, _translate("MainWindow", "1200 бод"))
        self.baudrate_box.setItemText(2, _translate("MainWindow", "2400 бод"))
        self.baudrate_box.setItemText(3, _translate("MainWindow", "4800 бод"))
        self.baudrate_box.setItemText(4, _translate("MainWindow", "9600 бод"))
        self.baudrate_box.setItemText(5, _translate("MainWindow", "19200 бод"))
        self.baudrate_box.setItemText(6, _translate("MainWindow", "38400 бод"))
        self.baudrate_box.setItemText(7, _translate("MainWindow", "57600 бод"))
        self.baudrate_box.setItemText(8, _translate("MainWindow", "74880 бод"))
        self.baudrate_box.setItemText(9, _translate("MainWindow", "115200 бод"))
        self.baudrate_box.setItemText(10, _translate("MainWindow", "230400 бод"))
        self.baudrate_box.setItemText(11, _translate("MainWindow", "250000 бод"))
        self.baudrate_box.setItemText(12, _translate("MainWindow", "500000 бод"))
        self.baudrate_box.setItemText(13, _translate("MainWindow", "1000000 бод"))
        self.baudrate_box.setItemText(14, _translate("MainWindow", "2000000 бод"))
        self.connect_btn.setText(_translate("MainWindow", "Подключиться"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.io_tab), _translate("MainWindow", "Соединение"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.export_tab), _translate("MainWindow", "Экспорт"))
        self.actionexport_as.setText(_translate("MainWindow", "export as..."))
